For all RPM's built on the local system (Ubuntu for now), updated to reference the "-nobuildreqs.spec" file so that the "BuildRequires: perl-ExtUtils-MakeMaker" directive is not used.  Using this results in the following error on an Ubuntu system where no software is installed/upgrade with RPM:
rpm: To install rpm packages on Debian systems, use alien. See README.Debian.
error: cannot open Packages index using db3 - No such file or directory (2)
error: cannot open Packages database in /var/lib/rpm



git-svn-id: file:///home/mbr/svn/gpgdir_repos/gpgdir/trunk@347 958e171a-1414-0410-8e2f-9d295d3c0db0